meta_product_name: "Elderly Share-a-Skill"
meta_title: "Elderly Share-a-Skill - An Old School Education with a Modern Twist"
meta_description: "Pairing retirees who have valuable skills to share with students eager to learn."
meta_image: "ESAS.meta.png" # should exist in `app/assets/images/`
twitter_account: "@a_elder"   # required for Twitter Cards
